### ISSUE TITLE
[docker] Virtualize workspaces for developers of Skycoin .NET apps

### ISSUE THREAD

**Issue by olemis** [simelo/libskycoin-dotnet#10]
Image name `simelotech/skycoindev-dotnet` and a single `develop` tag.

- [ ] .NET CLI tools built `FROM skycoin/skycoindev-cli:develop` 
- [ ] .NET CLI tools and Docker built `FROM skycoin/skycoindev-cli:dind` 
- [ ] .NET tools and VS Code IDE built `FROM skycoin/skycoindev-vscode:develop` 
- [ ] .NET tools, Docker and VS Code IDE built `FROM skycoin/skycoindev-vscode:dind`

**Comment by olemis** [comment]
@stdevHan please list the tools needed in side the container

**Comment by olemis** [comment]
@stdevPavelmc remind me to assign you this issue once you you accept invite to join this org .

**Comment by stdevYuniers** [comment]
@olemis I have parametrized docker builds to use all your proposals.
Later I will test If ibskycoin-dotnet build successful inside docker container.

**Comment by olemis** [comment]
Ready for merge ?

**Comment by olemis** [comment]
is there a PR ? what branch ?
