### ISSUE TITLE
Remove "-local" version suffix from NuGet package name

### ISSUE THREAD

**Issue by olemis** [simelo/libskycoin-dotnet#26]
NuGet package version includes `-local` suffix as can be noticed below.

<img width="866" alt="screen shot 2018-12-10 at 1 48 22 pm" src="https://user-images.githubusercontent.com/538253/49753813-7a251a00-fc82-11e8-9b31-6f10e26f939c.png">

It's necessary to remove it before package release since it's meant to be set only for identifying a working copy.

**Comment by olemis** [comment]
@olemis you should change that in code in the branch / PR for this 👆

**Comment by stdevHan** [comment]
Fixes [v0.26.0](https://github.com/simelo/libskycoin-dotnet/tree/0.26.0)
