### ISSUE TITLE
Tests for the .NET REST API wrappers

### ISSUE THREAD

**Issue by olemis** [simelo/libskycoin-dotnet#38]
## Expected Behavior

Same tests run for `SKY_api_*` functions shall be used for .NET API wrappers .

## Actual Behavior

... see #37 

## Specifications

  - Version: 0.25.0
  - Platform: all
  - Subsystem: all exported API sets

## Possible Solution

Reuse existing API test code, if any, and parameterize the invocation .

**Comment by stdevHan** [comment]
Fixes in [v0.26.0](https://github.com/simelo/libskycoin-dotnet/tree/0.26.0)
