### ISSUE TITLE
Update libskycoin submodule to 0.26.0

### ISSUE THREAD

**Issue by stdevMac** [simelo/libskycoin-dotnet#54]
## Feature description
Update the `libskycoin` submodule to 0.26.0

## Actual Behavior
Submodule tracks `skycoin/libskycoin@v0.25.1` .

## Specifications
* Version: 0.26.0
* Platform: all
* Subsystem: all

## Possible Solution
Update the libskycoin submodule to 0.26.0

**Comment by stdevHan** [comment]
Fixes in 440f44aeef53bb067d02e7b6cb507ac8e1d7e9f9
